name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_DEPLOYMENT }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: level-climber-463415-v3
        
    - name: Configure Docker to use Artifact Registry
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev


    - name: Build and Push Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/level-climber-463415-v3/test-repo/test-app ./app
        docker push us-central1-docker.pkg.dev/level-climber-463415-v3/test-repo/test-app

    - name: Install kubectl   
      run: |
        sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin

    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials test-cluster --region us-central1
        kubectl apply -f k8s/