name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: level-climber-463415-v3
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and Push Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/level-climber-463415-v3/test-repo/test-app ./app
        docker push us-central1-docker.pkg.dev/level-climber-463415-v3/test-repo/test-app

    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials devops-cluster --region us-central1
        kubectl apply -f k8s/